language: java
before_install:
  - chmod +x mvnw
script:
  - "mvn test"
deploy:
  provider: heroku
  api_key:
    secure: c2c4954e-58e8-4839-96c3-1536a132abc9
  app:
    master: integrador2018api
    test: integrador2018apitesting
  on:
    repo: jdvallejor/integrador2018api